name: Bump project version
on:
  push:
    branches: main
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup  NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Bump version
        run: |
          npm version patch --no-git-tag-version
          echo "new_version=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_ENV
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "Bump version to ${{ env.new_version }}"
      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
