name: Main workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: [lint]
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        version: [16.x, 18.x]
        exclude:
          - os: macos-latest
            version: 16.x
        include: 
            - os: ubuntu-latest
              version: 16.x
              is_ubuntu_16: "true"
    runs-on: ${{matrix.os}}
    env: 
      IS_UBUNTU_ON_NODE_16: ${{matrix.is_ubuntu_16}}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Install deps
        run: npm ci
      - name: Install browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
      - name: Check if running on ubuntu + node v16
        run: echo $IS_UBUNTU_ON_NODE_16
